#include "IdlTraitsCan.hpp"
#include "IdlTraitsEth.hpp"
#include "IdlTraitsFlexray.hpp"
#include "IdlTraitsGenericMessage.hpp"
#include "IdlTraitsIo.hpp"
#include "IdlTraitsLin.hpp"
#include "IdlTraitsSync.hpp"
