// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*! 
 * @file EthernetTopics.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _IB_SIM_ETH_IDL_ETHERNETTOPICS_H_
#define _IB_SIM_ETH_IDL_ETHERNETTOPICS_H_

// TODO Poner en el contexto.
#include "Common.h"

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif
#else
#define eProsima_user_DllExport
#endif

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(EthernetTopics_SOURCE)
#define EthernetTopics_DllAPI __declspec( dllexport )
#else
#define EthernetTopics_DllAPI __declspec( dllimport )
#endif // EthernetTopics_SOURCE
#else
#define EthernetTopics_DllAPI
#endif
#else
#define EthernetTopics_DllAPI
#endif // _WIN32

namespace eprosima
{
    namespace fastcdr
    {
        class Cdr;
    }
}

namespace ib
{
    namespace sim
    {
        namespace eth
        {
            namespace idl
            {
                /*!
                 * @brief This class represents the structure EthTagControlInformation defined by the user in the IDL file.
                 * @ingroup ETHERNETTOPICS
                 */
                class EthTagControlInformation
                {
                public:

                    /*!
                     * @brief Default constructor.
                     */
                    eProsima_user_DllExport EthTagControlInformation();

                    /*!
                     * @brief Default destructor.
                     */
                    eProsima_user_DllExport ~EthTagControlInformation();

                    /*!
                     * @brief Copy constructor.
                     * @param x Reference to the object ib::sim::eth::idl::EthTagControlInformation that will be copied.
                     */
                    eProsima_user_DllExport EthTagControlInformation(const EthTagControlInformation &x);

                    /*!
                     * @brief Move constructor.
                     * @param x Reference to the object ib::sim::eth::idl::EthTagControlInformation that will be copied.
                     */
                    eProsima_user_DllExport EthTagControlInformation(EthTagControlInformation &&x);

                    /*!
                     * @brief Copy assignment.
                     * @param x Reference to the object ib::sim::eth::idl::EthTagControlInformation that will be copied.
                     */
                    eProsima_user_DllExport EthTagControlInformation& operator=(const EthTagControlInformation &x);

                    /*!
                     * @brief Move assignment.
                     * @param x Reference to the object ib::sim::eth::idl::EthTagControlInformation that will be copied.
                     */
                    eProsima_user_DllExport EthTagControlInformation& operator=(EthTagControlInformation &&x);

                    /*!
                     * @brief This function sets a value in member pcp
                     * @param _pcp New value for member pcp
                     */
                    inline eProsima_user_DllExport void pcp(uint8_t _pcp)
                    {
                        m_pcp = _pcp;
                    }

                    /*!
                     * @brief This function returns the value of member pcp
                     * @return Value of member pcp
                     */
                    inline eProsima_user_DllExport uint8_t pcp() const
                    {
                        return m_pcp;
                    }

                    /*!
                     * @brief This function returns a reference to member pcp
                     * @return Reference to member pcp
                     */
                    inline eProsima_user_DllExport uint8_t& pcp()
                    {
                        return m_pcp;
                    }
                    /*!
                     * @brief This function sets a value in member dei
                     * @param _dei New value for member dei
                     */
                    inline eProsima_user_DllExport void dei(uint8_t _dei)
                    {
                        m_dei = _dei;
                    }

                    /*!
                     * @brief This function returns the value of member dei
                     * @return Value of member dei
                     */
                    inline eProsima_user_DllExport uint8_t dei() const
                    {
                        return m_dei;
                    }

                    /*!
                     * @brief This function returns a reference to member dei
                     * @return Reference to member dei
                     */
                    inline eProsima_user_DllExport uint8_t& dei()
                    {
                        return m_dei;
                    }
                    /*!
                     * @brief This function sets a value in member vid
                     * @param _vid New value for member vid
                     */
                    inline eProsima_user_DllExport void vid(uint16_t _vid)
                    {
                        m_vid = _vid;
                    }

                    /*!
                     * @brief This function returns the value of member vid
                     * @return Value of member vid
                     */
                    inline eProsima_user_DllExport uint16_t vid() const
                    {
                        return m_vid;
                    }

                    /*!
                     * @brief This function returns a reference to member vid
                     * @return Reference to member vid
                     */
                    inline eProsima_user_DllExport uint16_t& vid()
                    {
                        return m_vid;
                    }

                    /*!
                     * @brief This function returns the maximum serialized size of an object
                     * depending on the buffer alignment.
                     * @param current_alignment Buffer alignment.
                     * @return Maximum serialized size.
                     */
                    eProsima_user_DllExport static size_t getMaxCdrSerializedSize(size_t current_alignment = 0);

                    /*!
                     * @brief This function returns the serialized size of a data depending on the buffer alignment.
                     * @param data Data which is calculated its serialized size.
                     * @param current_alignment Buffer alignment.
                     * @return Serialized size.
                     */
                    eProsima_user_DllExport static size_t getCdrSerializedSize(const ib::sim::eth::idl::EthTagControlInformation& data, size_t current_alignment = 0);


                    /*!
                     * @brief This function serializes an object using CDR serialization.
                     * @param cdr CDR serialization object.
                     */
                    eProsima_user_DllExport void serialize(eprosima::fastcdr::Cdr &cdr) const;

                    /*!
                     * @brief This function deserializes an object using CDR serialization.
                     * @param cdr CDR serialization object.
                     */
                    eProsima_user_DllExport void deserialize(eprosima::fastcdr::Cdr &cdr);



                    /*!
                     * @brief This function returns the maximum serialized size of the Key of an object
                     * depending on the buffer alignment.
                     * @param current_alignment Buffer alignment.
                     * @return Maximum serialized size.
                     */
                    eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(size_t current_alignment = 0);

                    /*!
                     * @brief This function tells you if the Key has been defined for this type
                     */
                    eProsima_user_DllExport static bool isKeyDefined();

                    /*!
                     * @brief This function serializes the key members of an object using CDR serialization.
                     * @param cdr CDR serialization object.
                     */
                    eProsima_user_DllExport void serializeKey(eprosima::fastcdr::Cdr &cdr) const;

                private:
                    uint8_t m_pcp;
                    uint8_t m_dei;
                    uint16_t m_vid;
                };
                typedef uint32_t transmitIdT;
                /*!
                 * @brief This class represents the structure EthMessage defined by the user in the IDL file.
                 * @ingroup ETHERNETTOPICS
                 */
                class EthMessage
                {
                public:

                    /*!
                     * @brief Default constructor.
                     */
                    eProsima_user_DllExport EthMessage();

                    /*!
                     * @brief Default destructor.
                     */
                    eProsima_user_DllExport ~EthMessage();

                    /*!
                     * @brief Copy constructor.
                     * @param x Reference to the object ib::sim::eth::idl::EthMessage that will be copied.
                     */
                    eProsima_user_DllExport EthMessage(const EthMessage &x);

                    /*!
                     * @brief Move constructor.
                     * @param x Reference to the object ib::sim::eth::idl::EthMessage that will be copied.
                     */
                    eProsima_user_DllExport EthMessage(EthMessage &&x);

                    /*!
                     * @brief Copy assignment.
                     * @param x Reference to the object ib::sim::eth::idl::EthMessage that will be copied.
                     */
                    eProsima_user_DllExport EthMessage& operator=(const EthMessage &x);

                    /*!
                     * @brief Move assignment.
                     * @param x Reference to the object ib::sim::eth::idl::EthMessage that will be copied.
                     */
                    eProsima_user_DllExport EthMessage& operator=(EthMessage &&x);

                    /*!
                     * @brief This function copies the value in member senderAddr
                     * @param _senderAddr New value to be copied in member senderAddr
                     */
                    inline eProsima_user_DllExport void senderAddr(const ib::mw::idl::EndpointAddress &_senderAddr)
                    {
                        m_senderAddr = _senderAddr;
                    }

                    /*!
                     * @brief This function moves the value in member senderAddr
                     * @param _senderAddr New value to be moved in member senderAddr
                     */
                    inline eProsima_user_DllExport void senderAddr(ib::mw::idl::EndpointAddress &&_senderAddr)
                    {
                        m_senderAddr = std::move(_senderAddr);
                    }

                    /*!
                     * @brief This function returns a constant reference to member senderAddr
                     * @return Constant reference to member senderAddr
                     */
                    inline eProsima_user_DllExport const ib::mw::idl::EndpointAddress& senderAddr() const
                    {
                        return m_senderAddr;
                    }

                    /*!
                     * @brief This function returns a reference to member senderAddr
                     * @return Reference to member senderAddr
                     */
                    inline eProsima_user_DllExport ib::mw::idl::EndpointAddress& senderAddr()
                    {
                        return m_senderAddr;
                    }
                    /*!
                     * @brief This function sets a value in member transmitId
                     * @param _transmitId New value for member transmitId
                     */
                    inline eProsima_user_DllExport void transmitId(uint32_t _transmitId)
                    {
                        m_transmitId = _transmitId;
                    }

                    /*!
                     * @brief This function returns the value of member transmitId
                     * @return Value of member transmitId
                     */
                    inline eProsima_user_DllExport uint32_t transmitId() const
                    {
                        return m_transmitId;
                    }

                    /*!
                     * @brief This function returns a reference to member transmitId
                     * @return Reference to member transmitId
                     */
                    inline eProsima_user_DllExport uint32_t& transmitId()
                    {
                        return m_transmitId;
                    }
                    /*!
                     * @brief This function sets a value in member timestampNs
                     * @param _timestampNs New value for member timestampNs
                     */
                    inline eProsima_user_DllExport void timestampNs(int64_t _timestampNs)
                    {
                        m_timestampNs = _timestampNs;
                    }

                    /*!
                     * @brief This function returns the value of member timestampNs
                     * @return Value of member timestampNs
                     */
                    inline eProsima_user_DllExport int64_t timestampNs() const
                    {
                        return m_timestampNs;
                    }

                    /*!
                     * @brief This function returns a reference to member timestampNs
                     * @return Reference to member timestampNs
                     */
                    inline eProsima_user_DllExport int64_t& timestampNs()
                    {
                        return m_timestampNs;
                    }
                    /*!
                     * @brief This function copies the value in member rawFrame
                     * @param _rawFrame New value to be copied in member rawFrame
                     */
                    inline eProsima_user_DllExport void rawFrame(const std::vector<uint8_t> &_rawFrame)
                    {
                        m_rawFrame = _rawFrame;
                    }

                    /*!
                     * @brief This function moves the value in member rawFrame
                     * @param _rawFrame New value to be moved in member rawFrame
                     */
                    inline eProsima_user_DllExport void rawFrame(std::vector<uint8_t> &&_rawFrame)
                    {
                        m_rawFrame = std::move(_rawFrame);
                    }

                    /*!
                     * @brief This function returns a constant reference to member rawFrame
                     * @return Constant reference to member rawFrame
                     */
                    inline eProsima_user_DllExport const std::vector<uint8_t>& rawFrame() const
                    {
                        return m_rawFrame;
                    }

                    /*!
                     * @brief This function returns a reference to member rawFrame
                     * @return Reference to member rawFrame
                     */
                    inline eProsima_user_DllExport std::vector<uint8_t>& rawFrame()
                    {
                        return m_rawFrame;
                    }

                    /*!
                     * @brief This function returns the maximum serialized size of an object
                     * depending on the buffer alignment.
                     * @param current_alignment Buffer alignment.
                     * @return Maximum serialized size.
                     */
                    eProsima_user_DllExport static size_t getMaxCdrSerializedSize(size_t current_alignment = 0);

                    /*!
                     * @brief This function returns the serialized size of a data depending on the buffer alignment.
                     * @param data Data which is calculated its serialized size.
                     * @param current_alignment Buffer alignment.
                     * @return Serialized size.
                     */
                    eProsima_user_DllExport static size_t getCdrSerializedSize(const ib::sim::eth::idl::EthMessage& data, size_t current_alignment = 0);


                    /*!
                     * @brief This function serializes an object using CDR serialization.
                     * @param cdr CDR serialization object.
                     */
                    eProsima_user_DllExport void serialize(eprosima::fastcdr::Cdr &cdr) const;

                    /*!
                     * @brief This function deserializes an object using CDR serialization.
                     * @param cdr CDR serialization object.
                     */
                    eProsima_user_DllExport void deserialize(eprosima::fastcdr::Cdr &cdr);



                    /*!
                     * @brief This function returns the maximum serialized size of the Key of an object
                     * depending on the buffer alignment.
                     * @param current_alignment Buffer alignment.
                     * @return Maximum serialized size.
                     */
                    eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(size_t current_alignment = 0);

                    /*!
                     * @brief This function tells you if the Key has been defined for this type
                     */
                    eProsima_user_DllExport static bool isKeyDefined();

                    /*!
                     * @brief This function serializes the key members of an object using CDR serialization.
                     * @param cdr CDR serialization object.
                     */
                    eProsima_user_DllExport void serializeKey(eprosima::fastcdr::Cdr &cdr) const;

                private:
                    ib::mw::idl::EndpointAddress m_senderAddr;
                    uint32_t m_transmitId;
                    int64_t m_timestampNs;
                    std::vector<uint8_t> m_rawFrame;
                };
                /*!
                 * @brief This class represents the enumeration EthTransmitStatus defined by the user in the IDL file.
                 * @ingroup ETHERNETTOPICS
                 */
                enum EthTransmitStatus : uint32_t
                {
                    Transmitted,
                    ErrorControllerInactive,
                    ErrorLinkDown,
                    ErrorDropped,
                    ErrorDuplicatedTransmitId,
                    InvalidFrameFormat
                };
                /*!
                 * @brief This class represents the structure EthTransmitAcknowledge defined by the user in the IDL file.
                 * @ingroup ETHERNETTOPICS
                 */
                class EthTransmitAcknowledge
                {
                public:

                    /*!
                     * @brief Default constructor.
                     */
                    eProsima_user_DllExport EthTransmitAcknowledge();

                    /*!
                     * @brief Default destructor.
                     */
                    eProsima_user_DllExport ~EthTransmitAcknowledge();

                    /*!
                     * @brief Copy constructor.
                     * @param x Reference to the object ib::sim::eth::idl::EthTransmitAcknowledge that will be copied.
                     */
                    eProsima_user_DllExport EthTransmitAcknowledge(const EthTransmitAcknowledge &x);

                    /*!
                     * @brief Move constructor.
                     * @param x Reference to the object ib::sim::eth::idl::EthTransmitAcknowledge that will be copied.
                     */
                    eProsima_user_DllExport EthTransmitAcknowledge(EthTransmitAcknowledge &&x);

                    /*!
                     * @brief Copy assignment.
                     * @param x Reference to the object ib::sim::eth::idl::EthTransmitAcknowledge that will be copied.
                     */
                    eProsima_user_DllExport EthTransmitAcknowledge& operator=(const EthTransmitAcknowledge &x);

                    /*!
                     * @brief Move assignment.
                     * @param x Reference to the object ib::sim::eth::idl::EthTransmitAcknowledge that will be copied.
                     */
                    eProsima_user_DllExport EthTransmitAcknowledge& operator=(EthTransmitAcknowledge &&x);

                    /*!
                     * @brief This function copies the value in member senderAddr
                     * @param _senderAddr New value to be copied in member senderAddr
                     */
                    inline eProsima_user_DllExport void senderAddr(const ib::mw::idl::EndpointAddress &_senderAddr)
                    {
                        m_senderAddr = _senderAddr;
                    }

                    /*!
                     * @brief This function moves the value in member senderAddr
                     * @param _senderAddr New value to be moved in member senderAddr
                     */
                    inline eProsima_user_DllExport void senderAddr(ib::mw::idl::EndpointAddress &&_senderAddr)
                    {
                        m_senderAddr = std::move(_senderAddr);
                    }

                    /*!
                     * @brief This function returns a constant reference to member senderAddr
                     * @return Constant reference to member senderAddr
                     */
                    inline eProsima_user_DllExport const ib::mw::idl::EndpointAddress& senderAddr() const
                    {
                        return m_senderAddr;
                    }

                    /*!
                     * @brief This function returns a reference to member senderAddr
                     * @return Reference to member senderAddr
                     */
                    inline eProsima_user_DllExport ib::mw::idl::EndpointAddress& senderAddr()
                    {
                        return m_senderAddr;
                    }
                    /*!
                     * @brief This function sets a value in member transmitId
                     * @param _transmitId New value for member transmitId
                     */
                    inline eProsima_user_DllExport void transmitId(uint32_t _transmitId)
                    {
                        m_transmitId = _transmitId;
                    }

                    /*!
                     * @brief This function returns the value of member transmitId
                     * @return Value of member transmitId
                     */
                    inline eProsima_user_DllExport uint32_t transmitId() const
                    {
                        return m_transmitId;
                    }

                    /*!
                     * @brief This function returns a reference to member transmitId
                     * @return Reference to member transmitId
                     */
                    inline eProsima_user_DllExport uint32_t& transmitId()
                    {
                        return m_transmitId;
                    }
                    /*!
                     * @brief This function sets a value in member timestampNs
                     * @param _timestampNs New value for member timestampNs
                     */
                    inline eProsima_user_DllExport void timestampNs(int64_t _timestampNs)
                    {
                        m_timestampNs = _timestampNs;
                    }

                    /*!
                     * @brief This function returns the value of member timestampNs
                     * @return Value of member timestampNs
                     */
                    inline eProsima_user_DllExport int64_t timestampNs() const
                    {
                        return m_timestampNs;
                    }

                    /*!
                     * @brief This function returns a reference to member timestampNs
                     * @return Reference to member timestampNs
                     */
                    inline eProsima_user_DllExport int64_t& timestampNs()
                    {
                        return m_timestampNs;
                    }
                    /*!
                     * @brief This function sets a value in member status
                     * @param _status New value for member status
                     */
                    inline eProsima_user_DllExport void status(ib::sim::eth::idl::EthTransmitStatus _status)
                    {
                        m_status = _status;
                    }

                    /*!
                     * @brief This function returns the value of member status
                     * @return Value of member status
                     */
                    inline eProsima_user_DllExport ib::sim::eth::idl::EthTransmitStatus status() const
                    {
                        return m_status;
                    }

                    /*!
                     * @brief This function returns a reference to member status
                     * @return Reference to member status
                     */
                    inline eProsima_user_DllExport ib::sim::eth::idl::EthTransmitStatus& status()
                    {
                        return m_status;
                    }

                    /*!
                     * @brief This function returns the maximum serialized size of an object
                     * depending on the buffer alignment.
                     * @param current_alignment Buffer alignment.
                     * @return Maximum serialized size.
                     */
                    eProsima_user_DllExport static size_t getMaxCdrSerializedSize(size_t current_alignment = 0);

                    /*!
                     * @brief This function returns the serialized size of a data depending on the buffer alignment.
                     * @param data Data which is calculated its serialized size.
                     * @param current_alignment Buffer alignment.
                     * @return Serialized size.
                     */
                    eProsima_user_DllExport static size_t getCdrSerializedSize(const ib::sim::eth::idl::EthTransmitAcknowledge& data, size_t current_alignment = 0);


                    /*!
                     * @brief This function serializes an object using CDR serialization.
                     * @param cdr CDR serialization object.
                     */
                    eProsima_user_DllExport void serialize(eprosima::fastcdr::Cdr &cdr) const;

                    /*!
                     * @brief This function deserializes an object using CDR serialization.
                     * @param cdr CDR serialization object.
                     */
                    eProsima_user_DllExport void deserialize(eprosima::fastcdr::Cdr &cdr);



                    /*!
                     * @brief This function returns the maximum serialized size of the Key of an object
                     * depending on the buffer alignment.
                     * @param current_alignment Buffer alignment.
                     * @return Maximum serialized size.
                     */
                    eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(size_t current_alignment = 0);

                    /*!
                     * @brief This function tells you if the Key has been defined for this type
                     */
                    eProsima_user_DllExport static bool isKeyDefined();

                    /*!
                     * @brief This function serializes the key members of an object using CDR serialization.
                     * @param cdr CDR serialization object.
                     */
                    eProsima_user_DllExport void serializeKey(eprosima::fastcdr::Cdr &cdr) const;

                private:
                    ib::mw::idl::EndpointAddress m_senderAddr;
                    uint32_t m_transmitId;
                    int64_t m_timestampNs;
                    ib::sim::eth::idl::EthTransmitStatus m_status;
                };
                /*!
                 * @brief This class represents the enumeration EthState defined by the user in the IDL file.
                 * @ingroup ETHERNETTOPICS
                 */
                enum EthState : uint32_t
                {
                    Inactive,
                    LinkDown,
                    LinkUp
                };
                /*!
                 * @brief This class represents the structure EthStatus defined by the user in the IDL file.
                 * @ingroup ETHERNETTOPICS
                 */
                class EthStatus
                {
                public:

                    /*!
                     * @brief Default constructor.
                     */
                    eProsima_user_DllExport EthStatus();

                    /*!
                     * @brief Default destructor.
                     */
                    eProsima_user_DllExport ~EthStatus();

                    /*!
                     * @brief Copy constructor.
                     * @param x Reference to the object ib::sim::eth::idl::EthStatus that will be copied.
                     */
                    eProsima_user_DllExport EthStatus(const EthStatus &x);

                    /*!
                     * @brief Move constructor.
                     * @param x Reference to the object ib::sim::eth::idl::EthStatus that will be copied.
                     */
                    eProsima_user_DllExport EthStatus(EthStatus &&x);

                    /*!
                     * @brief Copy assignment.
                     * @param x Reference to the object ib::sim::eth::idl::EthStatus that will be copied.
                     */
                    eProsima_user_DllExport EthStatus& operator=(const EthStatus &x);

                    /*!
                     * @brief Move assignment.
                     * @param x Reference to the object ib::sim::eth::idl::EthStatus that will be copied.
                     */
                    eProsima_user_DllExport EthStatus& operator=(EthStatus &&x);

                    /*!
                     * @brief This function copies the value in member senderAddr
                     * @param _senderAddr New value to be copied in member senderAddr
                     */
                    inline eProsima_user_DllExport void senderAddr(const ib::mw::idl::EndpointAddress &_senderAddr)
                    {
                        m_senderAddr = _senderAddr;
                    }

                    /*!
                     * @brief This function moves the value in member senderAddr
                     * @param _senderAddr New value to be moved in member senderAddr
                     */
                    inline eProsima_user_DllExport void senderAddr(ib::mw::idl::EndpointAddress &&_senderAddr)
                    {
                        m_senderAddr = std::move(_senderAddr);
                    }

                    /*!
                     * @brief This function returns a constant reference to member senderAddr
                     * @return Constant reference to member senderAddr
                     */
                    inline eProsima_user_DllExport const ib::mw::idl::EndpointAddress& senderAddr() const
                    {
                        return m_senderAddr;
                    }

                    /*!
                     * @brief This function returns a reference to member senderAddr
                     * @return Reference to member senderAddr
                     */
                    inline eProsima_user_DllExport ib::mw::idl::EndpointAddress& senderAddr()
                    {
                        return m_senderAddr;
                    }
                    /*!
                     * @brief This function sets a value in member timestampNs
                     * @param _timestampNs New value for member timestampNs
                     */
                    inline eProsima_user_DllExport void timestampNs(int64_t _timestampNs)
                    {
                        m_timestampNs = _timestampNs;
                    }

                    /*!
                     * @brief This function returns the value of member timestampNs
                     * @return Value of member timestampNs
                     */
                    inline eProsima_user_DllExport int64_t timestampNs() const
                    {
                        return m_timestampNs;
                    }

                    /*!
                     * @brief This function returns a reference to member timestampNs
                     * @return Reference to member timestampNs
                     */
                    inline eProsima_user_DllExport int64_t& timestampNs()
                    {
                        return m_timestampNs;
                    }
                    /*!
                     * @brief This function sets a value in member state
                     * @param _state New value for member state
                     */
                    inline eProsima_user_DllExport void state(ib::sim::eth::idl::EthState _state)
                    {
                        m_state = _state;
                    }

                    /*!
                     * @brief This function returns the value of member state
                     * @return Value of member state
                     */
                    inline eProsima_user_DllExport ib::sim::eth::idl::EthState state() const
                    {
                        return m_state;
                    }

                    /*!
                     * @brief This function returns a reference to member state
                     * @return Reference to member state
                     */
                    inline eProsima_user_DllExport ib::sim::eth::idl::EthState& state()
                    {
                        return m_state;
                    }
                    /*!
                     * @brief This function sets a value in member bitRate
                     * @param _bitRate New value for member bitRate
                     */
                    inline eProsima_user_DllExport void bitRate(uint32_t _bitRate)
                    {
                        m_bitRate = _bitRate;
                    }

                    /*!
                     * @brief This function returns the value of member bitRate
                     * @return Value of member bitRate
                     */
                    inline eProsima_user_DllExport uint32_t bitRate() const
                    {
                        return m_bitRate;
                    }

                    /*!
                     * @brief This function returns a reference to member bitRate
                     * @return Reference to member bitRate
                     */
                    inline eProsima_user_DllExport uint32_t& bitRate()
                    {
                        return m_bitRate;
                    }

                    /*!
                     * @brief This function returns the maximum serialized size of an object
                     * depending on the buffer alignment.
                     * @param current_alignment Buffer alignment.
                     * @return Maximum serialized size.
                     */
                    eProsima_user_DllExport static size_t getMaxCdrSerializedSize(size_t current_alignment = 0);

                    /*!
                     * @brief This function returns the serialized size of a data depending on the buffer alignment.
                     * @param data Data which is calculated its serialized size.
                     * @param current_alignment Buffer alignment.
                     * @return Serialized size.
                     */
                    eProsima_user_DllExport static size_t getCdrSerializedSize(const ib::sim::eth::idl::EthStatus& data, size_t current_alignment = 0);


                    /*!
                     * @brief This function serializes an object using CDR serialization.
                     * @param cdr CDR serialization object.
                     */
                    eProsima_user_DllExport void serialize(eprosima::fastcdr::Cdr &cdr) const;

                    /*!
                     * @brief This function deserializes an object using CDR serialization.
                     * @param cdr CDR serialization object.
                     */
                    eProsima_user_DllExport void deserialize(eprosima::fastcdr::Cdr &cdr);



                    /*!
                     * @brief This function returns the maximum serialized size of the Key of an object
                     * depending on the buffer alignment.
                     * @param current_alignment Buffer alignment.
                     * @return Maximum serialized size.
                     */
                    eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(size_t current_alignment = 0);

                    /*!
                     * @brief This function tells you if the Key has been defined for this type
                     */
                    eProsima_user_DllExport static bool isKeyDefined();

                    /*!
                     * @brief This function serializes the key members of an object using CDR serialization.
                     * @param cdr CDR serialization object.
                     */
                    eProsima_user_DllExport void serializeKey(eprosima::fastcdr::Cdr &cdr) const;

                private:
                    ib::mw::idl::EndpointAddress m_senderAddr;
                    int64_t m_timestampNs;
                    ib::sim::eth::idl::EthState m_state;
                    uint32_t m_bitRate;
                };
                /*!
                 * @brief This class represents the enumeration EthMode defined by the user in the IDL file.
                 * @ingroup ETHERNETTOPICS
                 */
                enum EthMode : uint32_t
                {
                    ModeInactive,
                    ModeActive
                };
                /*!
                 * @brief This class represents the structure EthSetMode defined by the user in the IDL file.
                 * @ingroup ETHERNETTOPICS
                 */
                class EthSetMode
                {
                public:

                    /*!
                     * @brief Default constructor.
                     */
                    eProsima_user_DllExport EthSetMode();

                    /*!
                     * @brief Default destructor.
                     */
                    eProsima_user_DllExport ~EthSetMode();

                    /*!
                     * @brief Copy constructor.
                     * @param x Reference to the object ib::sim::eth::idl::EthSetMode that will be copied.
                     */
                    eProsima_user_DllExport EthSetMode(const EthSetMode &x);

                    /*!
                     * @brief Move constructor.
                     * @param x Reference to the object ib::sim::eth::idl::EthSetMode that will be copied.
                     */
                    eProsima_user_DllExport EthSetMode(EthSetMode &&x);

                    /*!
                     * @brief Copy assignment.
                     * @param x Reference to the object ib::sim::eth::idl::EthSetMode that will be copied.
                     */
                    eProsima_user_DllExport EthSetMode& operator=(const EthSetMode &x);

                    /*!
                     * @brief Move assignment.
                     * @param x Reference to the object ib::sim::eth::idl::EthSetMode that will be copied.
                     */
                    eProsima_user_DllExport EthSetMode& operator=(EthSetMode &&x);

                    /*!
                     * @brief This function copies the value in member senderAddr
                     * @param _senderAddr New value to be copied in member senderAddr
                     */
                    inline eProsima_user_DllExport void senderAddr(const ib::mw::idl::EndpointAddress &_senderAddr)
                    {
                        m_senderAddr = _senderAddr;
                    }

                    /*!
                     * @brief This function moves the value in member senderAddr
                     * @param _senderAddr New value to be moved in member senderAddr
                     */
                    inline eProsima_user_DllExport void senderAddr(ib::mw::idl::EndpointAddress &&_senderAddr)
                    {
                        m_senderAddr = std::move(_senderAddr);
                    }

                    /*!
                     * @brief This function returns a constant reference to member senderAddr
                     * @return Constant reference to member senderAddr
                     */
                    inline eProsima_user_DllExport const ib::mw::idl::EndpointAddress& senderAddr() const
                    {
                        return m_senderAddr;
                    }

                    /*!
                     * @brief This function returns a reference to member senderAddr
                     * @return Reference to member senderAddr
                     */
                    inline eProsima_user_DllExport ib::mw::idl::EndpointAddress& senderAddr()
                    {
                        return m_senderAddr;
                    }
                    /*!
                     * @brief This function sets a value in member mode
                     * @param _mode New value for member mode
                     */
                    inline eProsima_user_DllExport void mode(ib::sim::eth::idl::EthMode _mode)
                    {
                        m_mode = _mode;
                    }

                    /*!
                     * @brief This function returns the value of member mode
                     * @return Value of member mode
                     */
                    inline eProsima_user_DllExport ib::sim::eth::idl::EthMode mode() const
                    {
                        return m_mode;
                    }

                    /*!
                     * @brief This function returns a reference to member mode
                     * @return Reference to member mode
                     */
                    inline eProsima_user_DllExport ib::sim::eth::idl::EthMode& mode()
                    {
                        return m_mode;
                    }

                    /*!
                     * @brief This function returns the maximum serialized size of an object
                     * depending on the buffer alignment.
                     * @param current_alignment Buffer alignment.
                     * @return Maximum serialized size.
                     */
                    eProsima_user_DllExport static size_t getMaxCdrSerializedSize(size_t current_alignment = 0);

                    /*!
                     * @brief This function returns the serialized size of a data depending on the buffer alignment.
                     * @param data Data which is calculated its serialized size.
                     * @param current_alignment Buffer alignment.
                     * @return Serialized size.
                     */
                    eProsima_user_DllExport static size_t getCdrSerializedSize(const ib::sim::eth::idl::EthSetMode& data, size_t current_alignment = 0);


                    /*!
                     * @brief This function serializes an object using CDR serialization.
                     * @param cdr CDR serialization object.
                     */
                    eProsima_user_DllExport void serialize(eprosima::fastcdr::Cdr &cdr) const;

                    /*!
                     * @brief This function deserializes an object using CDR serialization.
                     * @param cdr CDR serialization object.
                     */
                    eProsima_user_DllExport void deserialize(eprosima::fastcdr::Cdr &cdr);



                    /*!
                     * @brief This function returns the maximum serialized size of the Key of an object
                     * depending on the buffer alignment.
                     * @param current_alignment Buffer alignment.
                     * @return Maximum serialized size.
                     */
                    eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(size_t current_alignment = 0);

                    /*!
                     * @brief This function tells you if the Key has been defined for this type
                     */
                    eProsima_user_DllExport static bool isKeyDefined();

                    /*!
                     * @brief This function serializes the key members of an object using CDR serialization.
                     * @param cdr CDR serialization object.
                     */
                    eProsima_user_DllExport void serializeKey(eprosima::fastcdr::Cdr &cdr) const;

                private:
                    ib::mw::idl::EndpointAddress m_senderAddr;
                    ib::sim::eth::idl::EthMode m_mode;
                };
            }
        }
    }
}

#endif // _IB_SIM_ETH_IDL_ETHERNETTOPICS_H_