// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file LinTopicsPubSubTypes.h
 * This header file contains the declaration of the serialization functions.
 *
 * This file was generated by the tool fastcdrgen.
 */


#ifndef _IB_SIM_LIN_IDL_LINTOPICS_PUBSUBTYPES_H_
#define _IB_SIM_LIN_IDL_LINTOPICS_PUBSUBTYPES_H_

#include <fastrtps/config.h>
#include <fastrtps/TopicDataType.h>

#include "LinTopics.h"

#if !defined(GEN_API_VER) || (GEN_API_VER != 1)
#error Generated LinTopics is not compatible with current installed Fast-RTPS. Please, regenerate it with fastrtpsgen.
#endif

namespace ib
{
    namespace sim
    {
        namespace lin
        {
            namespace idl
            {
                typedef uint8_t LinIdT;

                typedef uint8_t DataLengthT;
                /*!
                 * @brief This class represents the TopicDataType of the type Frame defined by the user in the IDL file.
                 * @ingroup LINTOPICS
                 */
                class FramePubSubType : public eprosima::fastrtps::TopicDataType {
                public:
                    typedef Frame type;

                    eProsima_user_DllExport FramePubSubType();

                    eProsima_user_DllExport virtual ~FramePubSubType();
                    eProsima_user_DllExport virtual bool serialize(void *data, eprosima::fastrtps::rtps::SerializedPayload_t *payload) override;
                    eProsima_user_DllExport virtual bool deserialize(eprosima::fastrtps::rtps::SerializedPayload_t *payload, void *data) override;
                    eProsima_user_DllExport virtual std::function<uint32_t()> getSerializedSizeProvider(void* data) override;
                    eProsima_user_DllExport virtual bool getKey(void *data, eprosima::fastrtps::rtps::InstanceHandle_t *ihandle,
                        bool force_md5 = false) override;
                    eProsima_user_DllExport virtual void* createData() override;
                    eProsima_user_DllExport virtual void deleteData(void * data) override;
                    MD5 m_md5;
                    unsigned char* m_keyBuffer;
                };



                /*!
                 * @brief This class represents the TopicDataType of the type FrameResponse defined by the user in the IDL file.
                 * @ingroup LINTOPICS
                 */
                class FrameResponsePubSubType : public eprosima::fastrtps::TopicDataType {
                public:
                    typedef FrameResponse type;

                    eProsima_user_DllExport FrameResponsePubSubType();

                    eProsima_user_DllExport virtual ~FrameResponsePubSubType();
                    eProsima_user_DllExport virtual bool serialize(void *data, eprosima::fastrtps::rtps::SerializedPayload_t *payload) override;
                    eProsima_user_DllExport virtual bool deserialize(eprosima::fastrtps::rtps::SerializedPayload_t *payload, void *data) override;
                    eProsima_user_DllExport virtual std::function<uint32_t()> getSerializedSizeProvider(void* data) override;
                    eProsima_user_DllExport virtual bool getKey(void *data, eprosima::fastrtps::rtps::InstanceHandle_t *ihandle,
                        bool force_md5 = false) override;
                    eProsima_user_DllExport virtual void* createData() override;
                    eProsima_user_DllExport virtual void deleteData(void * data) override;
                    MD5 m_md5;
                    unsigned char* m_keyBuffer;
                };

                typedef uint32_t BaudRateT;
                /*!
                 * @brief This class represents the TopicDataType of the type ControllerConfig defined by the user in the IDL file.
                 * @ingroup LINTOPICS
                 */
                class ControllerConfigPubSubType : public eprosima::fastrtps::TopicDataType {
                public:
                    typedef ControllerConfig type;

                    eProsima_user_DllExport ControllerConfigPubSubType();

                    eProsima_user_DllExport virtual ~ControllerConfigPubSubType();
                    eProsima_user_DllExport virtual bool serialize(void *data, eprosima::fastrtps::rtps::SerializedPayload_t *payload) override;
                    eProsima_user_DllExport virtual bool deserialize(eprosima::fastrtps::rtps::SerializedPayload_t *payload, void *data) override;
                    eProsima_user_DllExport virtual std::function<uint32_t()> getSerializedSizeProvider(void* data) override;
                    eProsima_user_DllExport virtual bool getKey(void *data, eprosima::fastrtps::rtps::InstanceHandle_t *ihandle,
                        bool force_md5 = false) override;
                    eProsima_user_DllExport virtual void* createData() override;
                    eProsima_user_DllExport virtual void deleteData(void * data) override;
                    MD5 m_md5;
                    unsigned char* m_keyBuffer;
                };

                /*!
                 * @brief This class represents the TopicDataType of the type Transmission defined by the user in the IDL file.
                 * @ingroup LINTOPICS
                 */
                class TransmissionPubSubType : public eprosima::fastrtps::TopicDataType {
                public:
                    typedef Transmission type;

                    eProsima_user_DllExport TransmissionPubSubType();

                    eProsima_user_DllExport virtual ~TransmissionPubSubType();
                    eProsima_user_DllExport virtual bool serialize(void *data, eprosima::fastrtps::rtps::SerializedPayload_t *payload) override;
                    eProsima_user_DllExport virtual bool deserialize(eprosima::fastrtps::rtps::SerializedPayload_t *payload, void *data) override;
                    eProsima_user_DllExport virtual std::function<uint32_t()> getSerializedSizeProvider(void* data) override;
                    eProsima_user_DllExport virtual bool getKey(void *data, eprosima::fastrtps::rtps::InstanceHandle_t *ihandle,
                        bool force_md5 = false) override;
                    eProsima_user_DllExport virtual void* createData() override;
                    eProsima_user_DllExport virtual void deleteData(void * data) override;
                    MD5 m_md5;
                    unsigned char* m_keyBuffer;
                };
                /*!
                 * @brief This class represents the TopicDataType of the type SendFrameRequest defined by the user in the IDL file.
                 * @ingroup LINTOPICS
                 */
                class SendFrameRequestPubSubType : public eprosima::fastrtps::TopicDataType {
                public:
                    typedef SendFrameRequest type;

                    eProsima_user_DllExport SendFrameRequestPubSubType();

                    eProsima_user_DllExport virtual ~SendFrameRequestPubSubType();
                    eProsima_user_DllExport virtual bool serialize(void *data, eprosima::fastrtps::rtps::SerializedPayload_t *payload) override;
                    eProsima_user_DllExport virtual bool deserialize(eprosima::fastrtps::rtps::SerializedPayload_t *payload, void *data) override;
                    eProsima_user_DllExport virtual std::function<uint32_t()> getSerializedSizeProvider(void* data) override;
                    eProsima_user_DllExport virtual bool getKey(void *data, eprosima::fastrtps::rtps::InstanceHandle_t *ihandle,
                        bool force_md5 = false) override;
                    eProsima_user_DllExport virtual void* createData() override;
                    eProsima_user_DllExport virtual void deleteData(void * data) override;
                    MD5 m_md5;
                    unsigned char* m_keyBuffer;
                };
                /*!
                 * @brief This class represents the TopicDataType of the type SendFrameHeaderRequest defined by the user in the IDL file.
                 * @ingroup LINTOPICS
                 */
                class SendFrameHeaderRequestPubSubType : public eprosima::fastrtps::TopicDataType {
                public:
                    typedef SendFrameHeaderRequest type;

                    eProsima_user_DllExport SendFrameHeaderRequestPubSubType();

                    eProsima_user_DllExport virtual ~SendFrameHeaderRequestPubSubType();
                    eProsima_user_DllExport virtual bool serialize(void *data, eprosima::fastrtps::rtps::SerializedPayload_t *payload) override;
                    eProsima_user_DllExport virtual bool deserialize(eprosima::fastrtps::rtps::SerializedPayload_t *payload, void *data) override;
                    eProsima_user_DllExport virtual std::function<uint32_t()> getSerializedSizeProvider(void* data) override;
                    eProsima_user_DllExport virtual bool getKey(void *data, eprosima::fastrtps::rtps::InstanceHandle_t *ihandle,
                        bool force_md5 = false) override;
                    eProsima_user_DllExport virtual void* createData() override;
                    eProsima_user_DllExport virtual void deleteData(void * data) override;
                    MD5 m_md5;
                    unsigned char* m_keyBuffer;
                };
                /*!
                 * @brief This class represents the TopicDataType of the type FrameResponseUpdate defined by the user in the IDL file.
                 * @ingroup LINTOPICS
                 */
                class FrameResponseUpdatePubSubType : public eprosima::fastrtps::TopicDataType {
                public:
                    typedef FrameResponseUpdate type;

                    eProsima_user_DllExport FrameResponseUpdatePubSubType();

                    eProsima_user_DllExport virtual ~FrameResponseUpdatePubSubType();
                    eProsima_user_DllExport virtual bool serialize(void *data, eprosima::fastrtps::rtps::SerializedPayload_t *payload) override;
                    eProsima_user_DllExport virtual bool deserialize(eprosima::fastrtps::rtps::SerializedPayload_t *payload, void *data) override;
                    eProsima_user_DllExport virtual std::function<uint32_t()> getSerializedSizeProvider(void* data) override;
                    eProsima_user_DllExport virtual bool getKey(void *data, eprosima::fastrtps::rtps::InstanceHandle_t *ihandle,
                        bool force_md5 = false) override;
                    eProsima_user_DllExport virtual void* createData() override;
                    eProsima_user_DllExport virtual void deleteData(void * data) override;
                    MD5 m_md5;
                    unsigned char* m_keyBuffer;
                };
                /*!
                 * @brief This class represents the TopicDataType of the type ControllerStatusUpdate defined by the user in the IDL file.
                 * @ingroup LINTOPICS
                 */
                class ControllerStatusUpdatePubSubType : public eprosima::fastrtps::TopicDataType {
                public:
                    typedef ControllerStatusUpdate type;

                    eProsima_user_DllExport ControllerStatusUpdatePubSubType();

                    eProsima_user_DllExport virtual ~ControllerStatusUpdatePubSubType();
                    eProsima_user_DllExport virtual bool serialize(void *data, eprosima::fastrtps::rtps::SerializedPayload_t *payload) override;
                    eProsima_user_DllExport virtual bool deserialize(eprosima::fastrtps::rtps::SerializedPayload_t *payload, void *data) override;
                    eProsima_user_DllExport virtual std::function<uint32_t()> getSerializedSizeProvider(void* data) override;
                    eProsima_user_DllExport virtual bool getKey(void *data, eprosima::fastrtps::rtps::InstanceHandle_t *ihandle,
                        bool force_md5 = false) override;
                    eProsima_user_DllExport virtual void* createData() override;
                    eProsima_user_DllExport virtual void deleteData(void * data) override;
                    MD5 m_md5;
                    unsigned char* m_keyBuffer;
                };
                /*!
                 * @brief This class represents the TopicDataType of the type WakeupPulse defined by the user in the IDL file.
                 * @ingroup LINTOPICS
                 */
                class WakeupPulsePubSubType : public eprosima::fastrtps::TopicDataType {
                public:
                    typedef WakeupPulse type;

                    eProsima_user_DllExport WakeupPulsePubSubType();

                    eProsima_user_DllExport virtual ~WakeupPulsePubSubType();
                    eProsima_user_DllExport virtual bool serialize(void *data, eprosima::fastrtps::rtps::SerializedPayload_t *payload) override;
                    eProsima_user_DllExport virtual bool deserialize(eprosima::fastrtps::rtps::SerializedPayload_t *payload, void *data) override;
                    eProsima_user_DllExport virtual std::function<uint32_t()> getSerializedSizeProvider(void* data) override;
                    eProsima_user_DllExport virtual bool getKey(void *data, eprosima::fastrtps::rtps::InstanceHandle_t *ihandle,
                        bool force_md5 = false) override;
                    eProsima_user_DllExport virtual void* createData() override;
                    eProsima_user_DllExport virtual void deleteData(void * data) override;
                    MD5 m_md5;
                    unsigned char* m_keyBuffer;
                };
            }
        }
    }
}

#endif // _IB_SIM_LIN_IDL_LINTOPICS_PUBSUBTYPES_H_