#include "Common.idl"

module ib {
module mw {
module logging {
module idl {

    module level {
        enum level_enum
        {
            trace,
            debug,
            info,
            warn,
            err,
            critical,
            off
        };
    };

    struct SourceLoc
    {
        string filename;
        unsigned long line;
        string funcname;
    };
    
    struct LogMsg
    {
        @Key ib::mw::idl::EndpointAddress senderAddr;
        string logger_name;
        level::level_enum level;
        long long timeUs; // time since UNIX epoch in Microseconds
        unsigned long long thread_id;
        unsigned long long msg_id;

        SourceLoc source;
        string payload;
    };

};
};
};
};
