// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*! 
 * @file MiddlewareTopicsPubSubTypes.h
 * This header file contains the declaration of the serialization functions.
 *
 * This file was generated by the tool fastcdrgen.
 */


#ifndef _IB_MW_SYNC_IDL_MIDDLEWARETOPICS_PUBSUBTYPES_H_
#define _IB_MW_SYNC_IDL_MIDDLEWARETOPICS_PUBSUBTYPES_H_

#include <fastrtps/config.h>
#include <fastrtps/TopicDataType.h>

#include "MiddlewareTopics.h"

#if !defined(GEN_API_VER) || (GEN_API_VER != 1)
#error Generated MiddlewareTopics is not compatible with current installed Fast-RTPS. Please, regenerate it with fastrtpsgen.
#endif

namespace ib
{
    namespace mw
    {
        namespace sync
        {
            namespace idl
            {
                /*!
                 * @brief This class represents the TopicDataType of the type QuantumRequest defined by the user in the IDL file.
                 * @ingroup MIDDLEWARETOPICS
                 */
                class QuantumRequestPubSubType : public eprosima::fastrtps::TopicDataType {
                public:
                        typedef QuantumRequest type;

                	QuantumRequestPubSubType();
                	virtual ~QuantumRequestPubSubType();
                	virtual bool serialize(void *data, eprosima::fastrtps::rtps::SerializedPayload_t *payload) override;
                	virtual bool deserialize(eprosima::fastrtps::rtps::SerializedPayload_t *payload, void *data) override;
                    virtual std::function<uint32_t()> getSerializedSizeProvider(void* data) override;
                	virtual bool getKey(void *data, eprosima::fastrtps::rtps::InstanceHandle_t *ihandle,
                		bool force_md5 = false) override;
                	virtual void* createData() override;
                	virtual void deleteData(void * data) override;
                	MD5 m_md5;
                	unsigned char* m_keyBuffer;
                };

                /*!
                 * @brief This class represents the TopicDataType of the type QuantumGrant defined by the user in the IDL file.
                 * @ingroup MIDDLEWARETOPICS
                 */
                class QuantumGrantPubSubType : public eprosima::fastrtps::TopicDataType {
                public:
                        typedef QuantumGrant type;

                	QuantumGrantPubSubType();
                	virtual ~QuantumGrantPubSubType();
                	virtual bool serialize(void *data, eprosima::fastrtps::rtps::SerializedPayload_t *payload) override;
                	virtual bool deserialize(eprosima::fastrtps::rtps::SerializedPayload_t *payload, void *data) override;
                    virtual std::function<uint32_t()> getSerializedSizeProvider(void* data) override;
                	virtual bool getKey(void *data, eprosima::fastrtps::rtps::InstanceHandle_t *ihandle,
                		bool force_md5 = false) override;
                	virtual void* createData() override;
                	virtual void deleteData(void * data) override;
                	MD5 m_md5;
                	unsigned char* m_keyBuffer;
                };
                /*!
                 * @brief This class represents the TopicDataType of the type Tick defined by the user in the IDL file.
                 * @ingroup MIDDLEWARETOPICS
                 */
                class TickPubSubType : public eprosima::fastrtps::TopicDataType {
                public:
                        typedef Tick type;

                	TickPubSubType();
                	virtual ~TickPubSubType();
                	virtual bool serialize(void *data, eprosima::fastrtps::rtps::SerializedPayload_t *payload) override;
                	virtual bool deserialize(eprosima::fastrtps::rtps::SerializedPayload_t *payload, void *data) override;
                    virtual std::function<uint32_t()> getSerializedSizeProvider(void* data) override;
                	virtual bool getKey(void *data, eprosima::fastrtps::rtps::InstanceHandle_t *ihandle,
                		bool force_md5 = false) override;
                	virtual void* createData() override;
                	virtual void deleteData(void * data) override;
                	MD5 m_md5;
                	unsigned char* m_keyBuffer;
                };
                /*!
                 * @brief This class represents the TopicDataType of the type TickDone defined by the user in the IDL file.
                 * @ingroup MIDDLEWARETOPICS
                 */
                class TickDonePubSubType : public eprosima::fastrtps::TopicDataType {
                public:
                        typedef TickDone type;

                	TickDonePubSubType();
                	virtual ~TickDonePubSubType();
                	virtual bool serialize(void *data, eprosima::fastrtps::rtps::SerializedPayload_t *payload) override;
                	virtual bool deserialize(eprosima::fastrtps::rtps::SerializedPayload_t *payload, void *data) override;
                    virtual std::function<uint32_t()> getSerializedSizeProvider(void* data) override;
                	virtual bool getKey(void *data, eprosima::fastrtps::rtps::InstanceHandle_t *ihandle,
                		bool force_md5 = false) override;
                	virtual void* createData() override;
                	virtual void deleteData(void * data) override;
                	MD5 m_md5;
                	unsigned char* m_keyBuffer;
                };

                /*!
                 * @brief This class represents the TopicDataType of the type ParticipantCommand defined by the user in the IDL file.
                 * @ingroup MIDDLEWARETOPICS
                 */
                class ParticipantCommandPubSubType : public eprosima::fastrtps::TopicDataType {
                public:
                        typedef ParticipantCommand type;

                	ParticipantCommandPubSubType();
                	virtual ~ParticipantCommandPubSubType();
                	virtual bool serialize(void *data, eprosima::fastrtps::rtps::SerializedPayload_t *payload) override;
                	virtual bool deserialize(eprosima::fastrtps::rtps::SerializedPayload_t *payload, void *data) override;
                    virtual std::function<uint32_t()> getSerializedSizeProvider(void* data) override;
                	virtual bool getKey(void *data, eprosima::fastrtps::rtps::InstanceHandle_t *ihandle,
                		bool force_md5 = false) override;
                	virtual void* createData() override;
                	virtual void deleteData(void * data) override;
                	MD5 m_md5;
                	unsigned char* m_keyBuffer;
                };

                /*!
                 * @brief This class represents the TopicDataType of the type SystemCommand defined by the user in the IDL file.
                 * @ingroup MIDDLEWARETOPICS
                 */
                class SystemCommandPubSubType : public eprosima::fastrtps::TopicDataType {
                public:
                        typedef SystemCommand type;

                	SystemCommandPubSubType();
                	virtual ~SystemCommandPubSubType();
                	virtual bool serialize(void *data, eprosima::fastrtps::rtps::SerializedPayload_t *payload) override;
                	virtual bool deserialize(eprosima::fastrtps::rtps::SerializedPayload_t *payload, void *data) override;
                    virtual std::function<uint32_t()> getSerializedSizeProvider(void* data) override;
                	virtual bool getKey(void *data, eprosima::fastrtps::rtps::InstanceHandle_t *ihandle,
                		bool force_md5 = false) override;
                	virtual void* createData() override;
                	virtual void deleteData(void * data) override;
                	MD5 m_md5;
                	unsigned char* m_keyBuffer;
                };

                /*!
                 * @brief This class represents the TopicDataType of the type ParticipantStatus defined by the user in the IDL file.
                 * @ingroup MIDDLEWARETOPICS
                 */
                class ParticipantStatusPubSubType : public eprosima::fastrtps::TopicDataType {
                public:
                        typedef ParticipantStatus type;

                	ParticipantStatusPubSubType();
                	virtual ~ParticipantStatusPubSubType();
                	virtual bool serialize(void *data, eprosima::fastrtps::rtps::SerializedPayload_t *payload) override;
                	virtual bool deserialize(eprosima::fastrtps::rtps::SerializedPayload_t *payload, void *data) override;
                    virtual std::function<uint32_t()> getSerializedSizeProvider(void* data) override;
                	virtual bool getKey(void *data, eprosima::fastrtps::rtps::InstanceHandle_t *ihandle,
                		bool force_md5 = false) override;
                	virtual void* createData() override;
                	virtual void deleteData(void * data) override;
                	MD5 m_md5;
                	unsigned char* m_keyBuffer;
                };

            }
        }
    }
}

#endif // _IB_MW_SYNC_IDL_MIDDLEWARETOPICS_PUBSUBTYPES_H_