// SPDX-FileCopyrightText: 2022 Vector Informatik GmbH
//
// SPDX-License-Identifier: MIT

#pragma once


#define DETAIL_SILKIT_DETAIL_NAMESPACE_NAME _detail_v1

#define DETAIL_SILKIT_DETAIL_VN_NAMESPACE_BEGIN namespace DETAIL_SILKIT_DETAIL_NAMESPACE_NAME {
#define DETAIL_SILKIT_DETAIL_VN_NAMESPACE_CLOSE }

#define DETAIL_SILKIT_CPP_API inline