name: build CMake preset
description: Build the given SIL Kit CMake preset

inputs:
  preset-name:
    description: "The preset name from CMakePresets.json."
    required: true
  cmake-args:
    description: "Additional CMake arguments"
    required: false
  run-tests:
    description: "Run tests"
    required: false
    default: true
    type: boolean
  artifact-label:
    type: string
    default: ""
    description: "Name of the artifact label to attach to uploads"
    required: true
  shell:
    type: string
    default: "bash"
    required: false
    description: "Explicitly set the shell to use for running cmake"
  extra-path:
    type: string
    default: ""
    required: false
    description: "Prepends this string to $PATH"
 
outputs:
  package-name:
    description: artifact name of the distribution zip
    value: "${{ steps.cmake-package.outputs.package-name }}"
  package-path:
    description: file path of the distribution zip
    value: "${{ steps.cmake-package.outputs.package-path }}"
  symbols-package-path:
    description: file path of the symbols zip
    value: "${{ steps.cmake-package.outputs.symbols-package-path }}"
  symbols-package-name:
    description: artifact name of the symbols zip
    value: "${{ steps.cmake-package.outputs.symbols-package-name }}"

runs:
  using: composite
  steps:

    - name: Configure ${{ inputs.preset-name }}
      run: |
        export PATH=${{ inputs.extra-path }}$PATH
        cmake --preset ${{ inputs.preset-name }} ${{ inputs.cmake-args }}
      shell: ${{ inputs.shell }}

    - name: Build ${{ inputs.preset-name }}
      run: |
        export PATH=${{ inputs.extra-path }}$PATH
        cmake --build --preset ${{ inputs.preset-name }}

      shell: ${{ inputs.shell }}

    - name: test ${{ inputs.preset-name }}
      if: ${{ inputs.run-tests == 'true' }}
      id: ctests
      run: |
        export PATH=${{ inputs.extra-path }}$PATH
        ctest --preset ${{ inputs.preset-name }} --output-on-failure -R '^(I|T)'

      shell: ${{ inputs.shell }}

    - name: stash test reports ${{ inputs.preset-name }}
      uses: actions/upload-artifact@v4
      with:
        name: "${{ inputs.artifact-label }}-test-results"
        path: '_build/**/*gtestresults.xml'
        retention-days: 2

    - name: create cmake package for ${{ inputs.preset-name }}
      id: cmake-package
      run: |
        export PATH=${{ inputs.extra-path }}$PATH
        cmake --build --preset ${{ inputs.preset-name }} --target package
        echo "package-name=$(basename _build/${{inputs.preset-name}}/_CPack_Packages/*/ZIP/SilKit-*-*/)-${{ inputs.artifact-label }}" >> $GITHUB_OUTPUT
        # keep our original zip, otherwise the execute bits are lost
        echo "package-path=$(echo _build/${{inputs.preset-name}}/_CPack_Packages/*/ZIP/SilKit-*-*.zip)" >> $GITHUB_OUTPUT
      shell: ${{ inputs.shell }}

    - name: upload package ${{ inputs.preset-name }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.cmake-package.outputs.package-name }}
        path: ${{ steps.cmake-package.outputs.package-path }}
        if-no-files-found: 'error'
        retention-days: 2
