name: build CMake preset
description: Build the given SIL Kit CMake preset

inputs:
  preset-name:
    description: "The preset name from CMakePresets.json."
    required: true
  cmake-args:
    description: "Additional CMake arguments"
    required: false
  run-tests:
    description: "Run tests"
    required: false
    default: true
    type: boolean
  toolset:
    type: string
    default: '14.1'
    description: "MSVC tool set to use"
    required: false
  build-arch:
    type: string
    default: "x64"
    description: "MSVC build architecture to use"
    required: false
  artifact-label:
    type: string
    default: ""
    description: "Name of the artifact label to attach to uploads"
    required: true
 
outputs:
  package-name:
    description: artifact name of the distribution zip
    value: "${{ steps.cmake-package.outputs.package-name }}"
  package-path:
    description: file path of the distribution zip
    value: "${{ steps.cmake-package.outputs.package-path }}"
  symbols-package-path:
    description: file path of the symbols zip
    value: "${{ steps.cmake-package.outputs.symbols-package-path }}"
  symbols-package-name:
    description: artifact name of the symbols zip
    value: "${{ steps.cmake-package.outputs.symbols-package-name }}"
 
runs:
  using: composite
  steps:

    - name: Setup host
      if: runner.os == 'Windows'
      run: |
        choco install -y ninja
        choco install -y doxygen.install
        pip install breathe==4.34.0
        pip install sphinx==5.1.1
        pip install sphinx-rtd-theme==1.0.0
      id: setup-host-windows
      shell: powershell

    - name: Setup host
      if: runner.os == 'macOS'
      run: brew install ninja doxygen
      id: setup-host-macos
      shell: bash

    - name: Prepare build env on Windows
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1.12.0
      with:
        arch: ${{ inputs.build-arch }}
        toolset: ${{ inputs.toolset }}
      id: setup-env-windows

    - name: Configure ${{ inputs.preset-name }}
      run: cmake --preset ${{ inputs.preset-name }} ${{ inputs.cmake-args }}
      id: cmake-configure
      shell: bash

    - name: Build ${{ inputs.preset-name }}
      id: cmake-build
      run: cmake --build --preset ${{ inputs.preset-name }}
      shell: bash

    - name: test ${{ inputs.preset-name }}
      if: ${{ inputs.run-tests == 'true' }}
      id: ctests
      run: ctest --preset ${{ inputs.preset-name }} --output-on-failure -R '^(I|T)'
      shell: bash

    - name: stash test reports ${{ inputs.preset-name }}
      uses: actions/upload-artifact@v4
      with:
        name: "${{ inputs.artifact-label }}-test-results"
        path: '_build/**/*gtestresults.xml'
        retention-days: 2

    - name: create cmake package for ${{ inputs.preset-name }}
      id: cmake-package
      run: |
        cmake --build --preset ${{ inputs.preset-name }} --target package
        echo "package-name=$(basename _build/${{inputs.preset-name}}/_CPack_Packages/*/ZIP/SilKit-*-*/)-${{ inputs.artifact-label }}" >> $GITHUB_OUTPUT
        # keep our original zip, otherwise the execute bits are lost
        echo "package-path=$(echo _build/${{inputs.preset-name}}/_CPack_Packages/*/ZIP/SilKit-*-*.zip)" >> $GITHUB_OUTPUT
      shell: bash

    - name: upload package ${{ inputs.preset-name }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.cmake-package.outputs.package-name }}
        path: ${{ steps.cmake-package.outputs.package-path }}
        if-no-files-found: 'error'
        retention-days: 2
