name: 'Linux Release Builds'
on:
  workflow_call:
    inputs:
      do_package:
        required: false
        type: boolean
        default: false
      do_package_symbols:
        required: false
        type: boolean
        default: false
      retention_days:
        required: false
        type: number
        default: 14
      run_build:
        required: true
        type: boolean

jobs:
  clang14-release:
    name: Clang 14 release Builds for Ubuntu 22.04
    environment: public-github-runners
    runs-on: ubuntu-22.04
    if: inputs.run_build == true
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ./.github/actions/build-cmake-preset
        with:
          preset-name: release
          cmake-args: "-D CMAKE_C_COMPILER=clang-14 -D CMAKE_CXX_COMPILER=clang++-14"
          do-package: ${{ inputs.do_package }}
          retention-days: ${{ inputs.retention_days }}

  gcc-release:
    name: GCC release Builds for Ubuntu 22.04
    environment: public-github-runners
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vectorgrp/sil-kit-docker-build/sil-kit-ci-ubuntu-22.04:main
    if: inputs.run_build == true
    steps:
      - name: git checkout
        uses: actions/checkout@v1
        with:
          submodules: true
      - name: GCC release build
        uses: ./.github/actions/build-cmake-preset
        id: build
        with:
          preset-name: release
          do-package: ${{ inputs.do_package }}
          retention-days: ${{ env.retention_days }}

