name: 'Windows Feature Branch Builds'
on:
  workflow_dispatch:
    inputs:
      do_package:
        required: true
        type: boolean
        default: true
      retention_days:
        required: true
        type: number
        default: 14

jobs:
  call_win_build:
    uses: ./.github/workflows/build-win.yml
    with:
      do_package: ${{ inputs.do_package }}
      retention_days: ${{ fromJSON(inputs.retention_days) }}

