name: 'Linux Feature Branch Builds'
on:
  workflow_dispatch:
    inputs:
      do_package:
        required: true
        type: boolean
        default: true
      do_package_symbols:
        required: true
        type: boolean
        default: false
      retention_days:
        required: true
        type: number
        default: 14

jobs:
  call_linux_build:
    uses: ./.github/workflows/build-linux.yml
    with:
      do_package: ${{ inputs.do_package }}
      retention_days: ${{ fromJSON(inputs.retention_days) }}

