name: 'Linux Release Builds'
on:
  workflow_call:
    inputs:
      do_package:
        required: false
        type: boolean
        default: false
      do_package_symbols:
        required: false
        type: boolean
        default: false
      retention_days:
        required: false
        type: number
        default: 14
      run_build:
        required: true
        type: boolean

jobs:
  clang14-release:
    name: Clang 14 release Builds for Ubuntu 22.04
    environment: public-github-runners
    runs-on: ubuntu-22.04
    if: inputs.run_build == true
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ./.github/actions/build-cmake-preset
        with:
          preset-name: clang14-release
          do-package: ${{ inputs.do_package }}
          retention-days: ${{ inputs.retention_days }}

  gcc8-release:
    name: GCC 8 release Builds for Ubuntu 18.04
    environment: public-github-runners
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mariusbgm/sil-kit-ci-ubuntu-18.04:main
    if: inputs.run_build == true
    steps:
      - name: install node20
        shell: bash
        run: |
          touch ~/.bash_profile
          wget -q -O - https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
          source ~/.bash_profile
          nvm install 20
          node -v

      - name: git checkout
        uses: actions/checkout@v1
        with:
          submodules: true
      - name: gcc8-release build
        uses: ./.github/actions/build-cmake-preset
        id: build
        with:
          preset-name: gcc8-release
          do-package: ${{ inputs.do_package }}
          retention-days: ${{ env.retention_days }}

