name: 'Linux Release Builds'
on:
  workflow_call:
    inputs:
      run_build:
        required: true
        type: boolean

jobs:
  ubuntu-release:
    strategy:
      matrix:
        toolchain:
          - cc: clang-18
            cxx: clang++-18
          - cc: gcc
            cxx: g++
    name: ${{ matrix.toolchain.cc }} release Builds for Ubuntu

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vectorgrp/sil-kit-docker-build/sil-kit-ci-public-runner:main
    if: (inputs.run_build == true) || (github.event_name == 'push')
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ./.github/actions/build-cmake-preset
        with:
          preset-name: linux-release
          cmake-args: "-DCMAKE_C_COMPILER=${{ matrix.toolchain.cc }} \
                       -DCMAKE_CXX_COMPILER=${{ matrix.toolchain.cxx }}"
          artifact-label: "${{ github.job }}-${{ matrix.toolchain.cc }}"
