name: 'Linux + Thread Sanitizer'
on:
  workflow_call:
    inputs:
      run_build:
        required: true
        type: boolean
        default: true
  workflow_dispatch:
    inputs:
      run_build:
        required: true
        type: boolean

  push:
    branches: [ 'main', 'dev_fix_linux-release_dirs']

jobs:
  clang-tsan:
    name: Thread Sanitizer Tests
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vectorgrp/sil-kit-docker-build/sil-kit-ci-public-runner:main
    if: (inputs.run_builds == true) || (github.event_name == 'push')
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ./.github/actions/build-cmake-preset
        with:
          preset-name: clang-relwithdebinfo
          do-package: false
          cmake-args: "-D SILKIT_ENABLE_THREADSAN=ON -D SILKIT_BUILD_DASHBOARD=OFF \
                       -DCMAKE_C_COMPILER=clang-18 \
                       -DCMAKE_CXX_COMPILER=clang++-18"
          testlog-name: ${{ github.job }}
