on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" # every hour 

jobs:
  sync_repo:
    name: Pull main branch from public GitHub to local branch
    runs-on: Linux
    environment: repo-sync-action/public-github
    permissions:
      contents: write
      actions: write
      deployments: write

    steps:
      - uses: actions/checkout@v3
        with:
          clean: true
          fetch-depth: 0

      - uses: vector-actions/repo-sync-action@main
        with:
          app-key:          ${{ secrets.VECTOR_APP_KEY }}
          app-id:           ${{ secrets.VECTOR_APP_ID }}
          remote-repo-url:  https://github.com/vectorgrp/sil-kit
          local-branch:     main-mirror
          remote-branch:    main
          sync-option:      pull-branch
